Generic
stackanetes/nova-kubernetes-drain pull request #2
Opened 2016-09-21 12:54 UTC by DTadrzak

WIP: 2. nova-kubernetes-prototype.

2016-09-27 18:56 UTC, DTadrzak commented
@ss7pro 
@PiotrProkop

2016-09-29 17:36 UTC, ss7pro commented on README.md
> + 1. Authorization from the configuration file.
Get authorization data from configuration file.

2016-09-29 17:37 UTC, ss7pro commented on README.md
> + 2. Determine the name of the running hypervisor in [OpenStack].
We need a separate section describing algorithm behind that.

2016-09-29 17:38 UTC, ss7pro commented on README.md
> + 6. Exit the application.
We need to add that this binary will not exit until all VMs are migrated or timeout is reached.

2016-09-29 17:38 UTC, ss7pro commented on README.md
> +A [Kubernetes] drain operation will make the application disable the scheduling of new VMs and perform live-evacuation of the currently running VMs. On the other hand, a [Kubernetes] uncordon operati
drain operation will disable scheduling of new VMs

2016-09-29 17:41 UTC, ss7pro commented on drainer.go
> +	timeOut := flag.Int("time-out", 30, "time out for live-migration")
for a live-migration.

2016-10-04 14:55 UTC, ss7pro commented on drainer.go
> +	if !*daemon {
I would prefer to have run-once option, so people would need to requested that explicitly.

2016-10-04 14:55 UTC, ss7pro commented on nova/utils.go
> +	for a := 1; a < 4; a++ {
4 should be somehow configurable, we should have a global api retry number variable (obtained from argv).

2016-10-04 14:55 UTC, ss7pro commented on nova/utils.go
> +	conn, err := net.Dial("udp", "keystone-api:5000")
s/udp/tcp

2016-10-04 14:55 UTC, ss7pro commented on nova/utils.go
> +		return "", fmt.Errorf("Cannot define ip address: %v", err)
Cannot get my ip address.

2016-10-04 14:55 UTC, ss7pro commented on nova/hypervisor.go
> +	if err != nil {
n.novaServices() should be called multiple times in case of error, we can also use rety count defined as argv.

2016-10-04 14:55 UTC, ss7pro commented on nova/hypervisor.go
> +	resp, err := n.client.Request("PUT", url, gophercloud.RequestOpts{
again, we should retry it multiple time in case of error.

2016-10-04 14:55 UTC, ss7pro commented on nova/hypervisor.go
> +		logger.Error.Println("Cannot change node state.")
again we should retry it multiple times in case of error.

2016-10-04 14:55 UTC, ss7pro commented on nova/hypervisor.go
> +	if err != nil {
same as above, retry multiple times in case of error.

2016-10-04 14:55 UTC, ss7pro commented on nova/hypervisor.go
> +	pager := servers.List(n.client, servers.ListOpts{
what happens here in case of network error ? is it retried ?

2016-10-04 14:55 UTC, ss7pro commented on nova/hypervisor.go
> +			for a := 1; a < liveMigrationRetry + 1; a++ {
this should be argv (liveMigrationRetry).

2016-10-04 14:55 UTC, ss7pro commented on nova/hypervisor.go
> +			for counter := 0; !migrated ; counter++ {
We should enter this loop only if we know that live migrate request was accepted.

2016-10-05 11:23 UTC, DTadrzak commented on nova/hypervisor.go
> +			for a := 1; a < liveMigrationRetry + 1; a++ {
It is a http call so we should have common variable for all http calls.

2016-10-06 06:53 UTC, DTadrzak commented on nova/hypervisor.go
> +	pager := servers.List(n.client, servers.ListOpts{
Function returns pager with error inside. So it gonna fail during converting pager to servers list.

2016-10-13 10:54 UTC, ss7pro commented on drainer.go
> +	timeOut := flag.Int("time-out", 30, "time out for a live-migration")
is it minutes, seconds ?

2016-10-13 10:59 UTC, Quentin-M commented
```
Oct 13 10:49:32 k8s-minion-4 rkt[22558]: [61166.594303] nova-drain[5]: Entrypoint Error: 2016/10/13 10:49:32 drainer.go:116: Error during watching: Cannot update hypervisior state: Cannot update hypervisor state: Cannot create obtain nova-compute services: %!v(MISSING), err
```

2016-10-13 11:00 UTC, ss7pro commented on nova/utils.go
> +	provider, err := openstack.AuthenticatedClient(ao)
we need retry here.

2016-10-13 13:59 UTC, Quentin-M commented
```
Oct 13 13:56:55 k8s-minion-5 rkt[15520]: [144837.344347] nova-drain[5]: Entrypoint WARNING: 2016/10/13 13:56:55 hypervisor.go:200: Attempt: 1. Cannot run migratation of VM ba9ea6d4-1251-47d6-87fa-597c0bc89845: Expected HTTP response code [201 202] when accessing [POST http://compute.openstack.cluster:30080/v2/f0d9a209a8f04e369e0ee63c5e80082a/servers/ba9ea6d4-1251-47d6-87fa-597c0bc89845/action], but got 400 instead
Oct 13 13:56:55 k8s-minion-5 rkt[15520]: [144837.344577] nova-drain[5]: {"badRequest": {"message": "k8s-minion-5 is not on local storage: Block migration can not be used with shared storage.", "code": 400}}.
```

2016-10-13 14:19 UTC, Quentin-M commented
I got one migration to work with local storage and then all my nova-drain pods when into a crash loop:

```
int INFO: 2016/10/13 14:16:03 drainer.go:41: Node Event found.
int INFO: 2016/10/13 14:16:03 drainer.go:46: Event belongs to node.
int Error: 2016/10/13 14:16:05 drainer.go:116: Error during watching: Cannot update hypervisior state: Cannot update hypervisor state: Cannot create obtain n
int Error: 2016/10/13 14:16:05 kubernetes-entrypoint.go:38: Executing command failed: exit status 1
```

2016-10-13 14:23 UTC, Quentin-M commented on nova/hypervisor.go
> +		return false, fmt.Errorf("Cannot create obtain nova-compute services: %v, err")
wrong " placement.

2016-10-13 15:27 UTC, Quentin-M commented
With the above error print statement fixed (thanks @DTadrzak), the error became quite clear.

```
Oct 13 14:38:42 k8s-minion-5 rkt[32740]: [147344.574201] nova-drain[5]: Entrypoint Error: 2016/10/13 14:38:42 drainer.go:121: Error during watching: Cannot update hypervisior state: Cannot update hypervisor state: Cannot obtain nova-compute services: Cannot gather openstack-service list: Get http://compute.openstack.cluster:30080/v2/f0d9a209a8f04e369e0ee63c5e80082a/os-services: dial tcp: lookup compute.openstack.cluster on 10.3.0.10:53: no such host
```

The tool is using the `publicURL` endpoint, which can't be resolved inside the cluster, it should instead use the `internalURL` one.

2016-10-14 13:49 UTC, Quentin-M requested changes

2016-10-14 13:49 UTC, Quentin-M commented on nova/utils.go
> +		client, err = openstack.NewComputeV2(provider, gophercloud.EndpointOpts{})
This option structure must contains: `Availability: gophercloud.AvailabilityInternal` to solve https://github.com/stackanetes/nova-kubernetes-drain/pull/2#issuecomment-253547554.

2016-10-21 09:47 UTC, merged